audio:
- .3ga
- .aa
- .aa3
- .aac
- .aax
- .abc
- .ac3
- .acd
- .acd-zip
- .acm
- .act
- .adg
- .adts
- .afc
- .ahx
- .aif
- .aifc
- .aiff
- .al
- .amr
- .amz
- .aob
- .apc
- .ape
- .apf
- .atrac
- .au
- .avr
- .awb
- .awb
- .bap
- .bmw
- .caf
- .cda
- .cfa
- .cidb
- .copy
- .cpr
- .cwp
- .dac
- .dcf
- .dcm
- .dct
- .dfc
- .dig
- .dsm
- .dss
- .dts
- .dtshd
- .dvf
- .efa
- .efe
- .efk
- .efv
- .emd
- .emx
- .enc
- .f64
- .fl
- .flac
- .flp
- .fst
- .g726
- .gnt
- .gpx
- .gsm
- .gsm
- .hma
- .htw
- .iff
- .iklax
- .imw
- .imy
- .its
- .ivc
- .k26
- .kar
- .kfn
- .koe
- .koz
- .koz
- .kpl
- .ktp
- .lqt
- .lvp
- .m3u
- .m3u8
- .m4a
- .m4b
- .m4p
- .m4r
- .ma1
- .mid
- .midi
- .miniusf
- .mio
- .mka
- .mmf
- .mon
- .mp2
- .mp3
- .mpa
- .mpc
- .mpu
- .mp_
- .msv
- .mt2
- .mte
- .mtp
- .mup
- .mxp4
- .mzp
- .ncor
- .nki
- .nrt
- .nsa
- .ntn
- .nwc
- .odm
- .oga
- .ogg
- .oma
- .omg
- .omx
- .ots
- .ove
- .pcast
- .pek
- .pla
- .pls
- .pna
- .prog
- .pvc
- .qcp
- .r1m
- .ra
- .ram
- .raw
- .rax
- .rex
- .rfl
- .rif
- .rmj
- .rns
- .rsd
- .rso
- .rti
- .rx2
- .sa1
- .sbr
- .sd2
- .sfa
- .sgt
- .sid
- .smf
- .snd
- .sng
- .sns
- .sprg
- .sseq
- .ssnd
- .swa
- .syh
- .sz
- .tap
- .trm
- .ul
- .usf
- .usflib
- .usm
- .vag
- .vmo
- .voi
- .vox
- .vpm
- .vrf
- .vy1
- .vyf
- .w01
- .w64
- .wav
- .wma
- .wproj
- .wrk
- .wus
- .wut
- .wwu
- .xfs
- .zgr
- .zvr
compressed:
- .mpkg
- .rar
- .pup
- .deb
- .s00
- .rte
- .gz2
- .gzip
- .vip
- .xapk
- .tbz
- .pkg.tar.xz
- .lemon
- .sy_
- .sit
- .comppkg.hauptwerk.rar
- .b6z
- .7z
- .dl_
- .bz2
- .dz
- .pkg
- .r00
- .uha
- .sqx
- .qda
- .fzpz
- .ice
- .mint
- .f3z
- .lzm
- .dar
- .r2
- .rp9
- .wa
- .ecs
- .tar.lzma
- .gza
- .hbe
- .sifz
- .bndl
- .zpi
- .arduboy
- .pbi
- .7z.002
- .smpf
- .zip
- .par
- .pf
- .b1
- .pak
- .cbr
- .cbz
- .rev
- .jar.pack
- .tar.xz
- .jsonlz4
- .ita
- .nex
- .ark
- .taz
- .rpm
- .kgb
- .pit
- .pwa
- .npk
- .f
- .spd
- .sfg
- .xip
- .pcv
- .bh
- .cdz
- .pea
- .a02
- .c00
- .gz
- .tx_
- .bundle
- .car
- .tar.lz
- .s7z
- .hki
- .apz
- .yz
- .lzma
- .zix
- .ar
- .cxarchive
- .sfx
- .alz
- .ari
- .czip
- .7z.001
- .z03
- .piz
- .opk
- .ctz
- .archiver
- .arc
- .r01
- .bz
- '.0'
- .sitx
- .ipk
- .snb
- .war
- .z
- .gmz
- .a01
- .zipx
- .ace
- .cbt
- .fdp
- .r03
- .ufs.uzip
- .voca
- .shar
- .p19
- .tar.bz2
- .oz
- .sdn
- .xx
- .zst
- .lpkg
- .tbz2
- .ba
- .c10
- .epi
- .pa
- .s01
- .oar
- .mbz
- .gca
- .s02
- .rnc
- .zl
- .cb7
- .ctx
- .package
- .tgz
- .sdc
- .xz
- .sea
- .r30
- .arj
- .dd
- .tar.gz
- .snappy
- .spt
- .par2
- .rz
- .mzp
- .a00
- .pup
- .c01
- .sfs
- .zfsendtotarget
- .xez
- .whl
- .sh
- .r0
- .gzi
- .fp8
- .lhzd
- .paq8p
- .jhh
- '.000'
- .edz
- .lz
- .zsplit
- .z02
- .jgz
- .xar
- .rk
- .lbr
- .z04
- .hyp
- .shr
- .pet
- .iadproj
- .tcx
- .j
- .bzip2
- .lzh
- .srep
- .zoo
- .pax
- .z01
- .ize
- .sar
- .agg
- .vsi
- .ain
- .efw
- .ipg
- .vmcz
- .fzbz
- .zap
- .lzo
- .warc
- .xmcdz
- .uc2
- .hbc
- .wdz
- .paq8f
- .zz
- .hki1
- .dgc
- .bza
- .zi
- .isx
- .libzip
- .cpt
- .zw
- .asr
- .lqr
- .cba
- .mzp
- .nz
- .lnx
- .r04
- .tz
- .arh
- .hki3
- .md
- .txz
- .egg
- .cpgz
- .wux
- .lha
- .layout
- .wastickers
- .spm
- .rss
- .tg
- .pack.gz
- .xzm
- .hpk
- .si
- .b64
- .bzip
- .c02
- .vpk
- .xef
- .pae
- .yz1
- .hpkg
- .jic
- .paq6
- .zi_
- .waff
- .tar.z
- .puz
- .uzip
- .bdoc
- .mou
- .r02
- .tlz
- .kz
- .trs
- .dist
- .sbx
- .r21
- .tlzma
- .p01
- .r1
- .tar.gz2
- .paq8l
- .sen
- .vem
- .psz
- .wlb
- .ha
- .p7z
- .hki2
- .pvmz
- .tzst
- .spl
- .s09
- .prs
- .lzx
- .comppkg_hauptwerk_rar
- .apex
- .stproj
- .vwi
- .jex
- .ayt
- .cp9
- .hbc2
- .vfs
- .paq7
- .ish
- .daf
- .boo
- .paq8
- .y
- .pim
- .sbx
- .wot
- .shk
- .sqz
- .ecsbx
- .gar
document:
- .doc
- .dot
- .wbk
- .docx
- .docm
- .dotx
- .dotm
- .docb
- .xls
- .xlt
- .xlm
- .xlsx
- .xlsm
- .xltx
- .xltm
- .xlsb
- .xla
- .xlam
- .xll
- .xlw
- .ppt
- .pot
- .pps
- .pptx
- .pptm
- .potx
- .potm
- .ppam
- .ppsx
- .ppsm
- .sldx
- .sldm
- .pub
- .xps
programs:
- .exe
video:
- 3g2
- 3gp
- aaf
- asf
- avchd
- avi
- drc
- flv
- m2v
- m4p
- m4v
- mkv
- mng
- mov
- mp2
- mp4
- mpe
- mpeg
- mpg
- mpv
- mxf
- nsv
- ogg
- ogv
- qt
- rm
- rmvb
- roq
- svi
- vob
- webm
- wmv
- yuv
